spring.application.name=guarinve
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://db:5432/microservice_egv
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Debe ser EXACTAMENTE el mismo valor que jwt.secret en todos-service
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
